apiVersion: v1
kind: Pod
metadata:
  name: reader-pod
spec:
  containers:
    - name: reader-container
      image: busybox
      command: ["/bin/sh", "-c", "cat /mnt/data/hello.txt && sleep 3600"]
      volumeMounts:
        - name: shared-storage
          mountPath: /mnt/data
  volumes:
    - name: shared-storage
      persistentVolumeClaim:
        claimName: my-pvc